# Generated by Django 5.2.1 on 2025-05-21 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_match_round_match_season_match_status_alter_match_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possession', models.CharField(blank=True, help_text='Topla oynama istatistiği (ör: 55%-45%)', max_length=10)),
                ('shots', models.CharField(blank=True, help_text='Şut istatistiği (ör: 12-8)', max_length=10)),
                ('shots_on_target', models.CharField(blank=True, help_text='İsabetli şut (ör: 5-3)', max_length=10)),
                ('corners', models.CharField(blank=True, help_text='Korner (ör: 7-4)', max_length=10)),
                ('fouls', models.CharField(blank=True, help_text='Faul (ör: 10-12)', max_length=10)),
                ('yellows', models.CharField(blank=True, help_text='Sarı kart (ör: 3-2)', max_length=10)),
                ('reds', models.CharField(blank=True, help_text='Kırmızı kart (ör: 1-0)', max_length=10)),
                ('analysis_text', models.TextField(blank=True, help_text='Maç analiz yazısı')),
                ('key_moments', models.JSONField(blank=True, default=list, help_text='Maçın önemli anları listesi')),
                ('player_ratings', models.JSONField(blank=True, default=dict, help_text='Oyuncu puanları')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='scores.match')),
            ],
        ),
        migrations.CreateModel(
            name='MatchPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_form', models.CharField(blank=True, help_text='Son 5 maç (ör: WWLDW)', max_length=50)),
                ('away_form', models.CharField(blank=True, help_text='Son 5 maç (ör: WWLDW)', max_length=50)),
                ('home_stats', models.JSONField(blank=True, default=dict, help_text='Ev sahibi takım istatistikleri')),
                ('away_stats', models.JSONField(blank=True, default=dict, help_text='Deplasman takım istatistikleri')),
                ('key_players', models.TextField(blank=True, help_text='Maçın kilit oyuncuları')),
                ('prediction', models.CharField(blank=True, help_text='Maç tahmini', max_length=100)),
                ('preview_text', models.TextField(blank=True, help_text='Maç önizleme yazısı')),
                ('head_to_head', models.JSONField(blank=True, default=dict, help_text='Karşılıklı maç istatistikleri')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preview', to='scores.match')),
            ],
        ),
    ]
