# Generated by Django 5.2.1 on 2025-05-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_matchanalysis_matchpreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_leagues',
            field=models.ManyToManyField(blank=True, related_name='fans', to='scores.league'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_players',
            field=models.ManyToManyField(blank=True, related_name='fans', to='scores.player'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notification_method',
            field=models.CharField(choices=[('push', 'Push Bildirimi'), ('email', 'E-Posta'), ('both', 'Her İkisi')], default='push', max_length=10, verbose_name='Bildirim Yöntemi'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notification_settings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_goals',
            field=models.BooleanField(default=True, verbose_name='Gol Bildirimleri'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_important_events',
            field=models.BooleanField(default=True, verbose_name='Önemli Olaylar'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_lineup',
            field=models.BooleanField(default=True, verbose_name='İlk 11 Bildirimleri'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_match_start',
            field=models.BooleanField(default=True, verbose_name='Maç Başlama Bildirimleri'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_red_cards',
            field=models.BooleanField(default=True, verbose_name='Kırmızı Kart Bildirimleri'),
        ),
    ]
